/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.sql.SQLException;

/**
 *
 * @author vini pandhare
 */
public class DashboardFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashboardFrame.class.getName());

    /**
     * Creates new form DashboardFrame
     */
    public DashboardFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDashboard = new javax.swing.JTextArea();
        btnAddExpense = new javax.swing.JButton();
        btnViewExpenses = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnSetBudget = new javax.swing.JButton();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Budget Dashboard");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setText("Budget Dashboard");

        txtDashboard.setEditable(false);
        txtDashboard.setColumns(20);
        txtDashboard.setRows(5);
        jScrollPane1.setViewportView(txtDashboard);

        btnAddExpense.setText("Add Expense");
        btnAddExpense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddExpenseActionPerformed(evt);
            }
        });

        btnViewExpenses.setText("View Expenses");
        btnViewExpenses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewExpensesActionPerformed(evt);
            }
        });

        btnRefresh.setText("Refresh Dashboard");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnSetBudget.setText("Set Budget");
        btnSetBudget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetBudgetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(112, 112, 112))
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSetBudget)
                    .addComponent(btnRefresh)
                    .addComponent(btnViewExpenses)
                    .addComponent(btnAddExpense)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAddExpense)
                .addGap(18, 18, 18)
                .addComponent(btnViewExpenses)
                .addGap(18, 18, 18)
                .addComponent(btnRefresh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSetBudget)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddExpenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddExpenseActionPerformed

        AddExpensesFrame frame =
        new AddExpensesFrame();

frame.setVisible(true);
    }//GEN-LAST:event_btnAddExpenseActionPerformed

    private void btnViewExpensesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewExpensesActionPerformed
        // TODO add your handling code here:
        ViewExpensesFrame frame =
        new ViewExpensesFrame();

frame.setVisible(true);
    }//GEN-LAST:event_btnViewExpensesActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
 try {

        java.sql.Connection con =
                util.DBconnection.getConnection();

        double totalBudget = 0;
        double totalExpense = 0;

        String budgetSql =
                "SELECT SUM(budget_amount) FROM budgets";

        java.sql.PreparedStatement pst1 =
                con.prepareStatement(budgetSql);

        java.sql.ResultSet rs1 =
                pst1.executeQuery();

        if(rs1.next()) {

            totalBudget =
                    rs1.getDouble(1);
        }

        String expenseSql =
                "SELECT SUM(amount) FROM expenses";

        java.sql.PreparedStatement pst2 =
                con.prepareStatement(expenseSql);

        java.sql.ResultSet rs2 =
                pst2.executeQuery();

        if(rs2.next()) {

            totalExpense =
                    rs2.getDouble(1);
        }

        double remaining =
                totalBudget - totalExpense;

        double usage = 0;

        if(totalBudget > 0) {

            usage =
                    (totalExpense / totalBudget)
                    * 100;
        }

        txtDashboard.setText(

                "Total Budget : ₹"
                + totalBudget

                + "\n\nTotal Expense : ₹"
                + totalExpense

                + "\n\nRemaining : ₹"
                + remaining

                + "\n\nUsage : "
                + String.format("%.2f", usage)
                + "%"

        );

    } catch(SQLException e){

        javax.swing.JOptionPane.showMessageDialog(
                this,
                e.getMessage());
    }
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnSetBudgetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetBudgetActionPerformed
        // TODO add your handling code here:
    new BudgetSetupFrame().setVisible(true);

    }//GEN-LAST:event_btnSetBudgetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DashboardFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddExpense;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSetBudget;
    private javax.swing.JButton btnViewExpenses;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtDashboard;
    // End of variables declaration//GEN-END:variables
}
